project:
  type: manuscript

manuscript:
  article: article.qmd
  resources:
    - data/Boehnke_et_al.csv
    - data/CO2_rMELTS_ZR_calib.c
    - data/CO2_rMELTS_ZR_calib.h
    - data/Gervasoni_2016.xlsx
    - data/H2O_rMELTS_ZR_calib.c
    - data/H2O_rMELTS_ZR_calib.h
    - data/support_scripts.py
    - data/Watson_and_Harrison.csv
  # code-links: [repo, devcontainer, binder]
  notebooks:
    - notebooks/1-Model-description.ipynb
    - notebooks/2-Endmembers-MELTS.ipynb
    - notebooks/3-Liquid-MELTS-codegen.ipynb
    - notebooks/4-Liquid-MELTS-API-tests.ipynb
    - notebooks/5-Liquid-MELTS-calib-1.ipynb
    - notebooks/6-Liquid-MELTS-calib-2.ipynb
    - notebooks/7-MELTS-with-Zr.ipynb

format:
  html:
    theme: cosmo
    comments: 
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc-location: left
    title-block-style: manuscript
  agu-pdf: 
    notebook-links: inline
  docx: default
  jats: default

citation:
  container-title: Earth and Space Science
  type: article-journal
  issued: 2023-05-01
  doi: "10.1136/bmj.m4290"

